name: Remote SSH
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/jsmarchewka/domains/jsmarchewka.pl/public_html/home/home-budget
          ssh-add ~/.ssh/id_ed25519
          git pull
          php81 ~/composer-stable.phar install
          php81 bin/console doctrine:migration:migrate --no-interaction
          source /home/jsmarchewka/nodevenv/domains/jsmarchewka.pl/public_html/home/home-budget/16/bin/activate && cd /home/jsmarchewka/domains/jsmarchewka.pl/public_html/home/home-budget
          npm run build
